name: movies
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: "^3.5.0"

dependencies:
  flutter:
    sdk: flutter
  # Other direct dependencies
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^2.0.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.5
  flutter_lints: ^4.0.0 # Linting rules for Flutter
  lints: ^4.0.0 # General Dart linting rules

dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0
  _fe_analyzer_shared: ^73.0.0
  analyzer: ^6.8.0
  http_parser: ^4.1.0
  shelf: ^1.4.2
  string_scanner: ^1.3.0
  test_api: ^0.7.3
